[build]
  command = "npm run build:client"
  publish = "dist/spa"

[build.environment]
  PNPM_FLAGS = "--no-frozen-lockfile"

[[redirects]]
  from = "/api/*"
  to = "https://multi-bakend.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
